# Generated by Django 6.1.1 on 2026-10-03 02:46

import datetime
import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid username.", regex="^[a-z0-9_]+$"
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("fda", "Front Desk Agent"),
                            ("op-m", "Operation Manager"),
                            ("gen-m", "General Manager"),
                            ("employee", "Employee"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number_code",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid phone number code.",
                                regex="^\\+[0-9]+$",
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid phone number.", regex="^[0-9]+$"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_confirmed_at", models.DateTimeField(null=True)),
                (
                    "email_confirmation_token",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "email_confirmation_expiresat",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 10, 3, 3, 46, 53, 334573, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                    ),
                ),
                ("avatar_url", models.CharField(max_length=255, null=True)),
                (
                    "first_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid name.", regex="^[a-zA-Z ]+$"
                            )
                        ],
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid name.", regex="^[a-zA-Z ]+$"
                            )
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid name.", regex="^[a-zA-Z ]+$"
                            )
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
